###################################
#                                 #
#         CustomsMessage          #
#          Version 1.7            #
###################################

#If you don't know what to do, join our discord, where we will give you advice.
# https://discord.gg/nE2YhqWzDZ

# Used to let the plugin determine if your config is up-to-date, so a
# warning can be printed in the server console. Only edit this if you
# know what you are doing, or have just updated your config to the
# newest version.
config-version: '1.4'

#Commands/Permissions:

#/reload message.reload

#Edit first join message!
First-join: "&ePlayer &6%player% &ejoined for the first time!"

#Customs Join and Leave message
Join-Message: "&a[+] %player%"
Leave-Message: "&c[-] %player%"

#Plugin message settings
Reload: "&7Reload plugin was successful."
Prefix: "&e[&6CustomsMessage&e]"