name: Message
version: '2.0'
main: me.hesovodoupe.message.Message
api-version: '1.16'
author: Ondraeucz
description: Customs message (First, Join, Leave)
depend:
  - PlaceholderAPI
commands:
  customsmessage:
    description: /cm reload
    aliases:
      - cm