name: Message
version: '1.3-SNAPSHOT'
main: me.hesovodoupe.message.Message
api-version: '1.19'
author: Ondraeucz
description: CustomsJoin and Leave message <3
softdepend:
  - PlaceholderAPI
  - LuckPerms

commands:
  customsmessage:
    description: /reload
    aliases:
      - cm